version: "3.4"
services:
  api:
    image: adoptopenjdk:11-jre-hotspot
    container_name: app-workflow
    privileged: true
    working_dir: /webapps
    extra_hosts:
      - "mysqlserver:192.168.65.2"
    volumes: 
      - ./app/target:/webapps
      - ./config/application-dev.yml:/webapps/config/application-dev.yml
    ports: 
      - 8080:8080
    command:
      - /bin/sh
      - -c
      - |
        java -jar *.jar --sprint.profiles.active=dev --server.port=8080

networks:
  default:
    name: api_uaas_network
    
    