version: '3.4'
services:
  mysqlserver:
    image: daocloud.io/library/mysql:5.7
    container_name: mysqlserver
    privileged: true
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: uaas
    volumes:
        - ./mysql.conf.d/sql_mode.cnf:/etc/mysql/mysql.conf.d/sql_mode.cnf

networks:
  default:
    name: api_uaas_network
    external: true
