version: '3.4'
services:
  mysqlserver_nginx:
    image: daocloud.io/library/nginx:latest
    container_name: mysqlserver_nginx
    privileged: true
    network_mode: host
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
